<?php

namespace AppBundle\Repository;

/**
 * TranslateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TranslateRepository extends \Doctrine\ORM\EntityRepository
{
}
